"""updates to invoice model

Revision ID: 1e199ed3442f
Revises: 6686a718549b
Create Date: 2025-11-18 22:45:38.249103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e199ed3442f'
down_revision: Union[str, Sequence[str], None] = '6686a718549b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema by dropping old columns and adding new ones with the correct type."""
    # ### commands auto generated by Alembic - please adjust! ###

    # --- INVOICES TABLE COLUMN DROPS AND ADDS ---

    # 1. Drop old payee_party (VARCHAR) and add new payee_party (JSON)
    op.drop_column('invoices', 'payee_party')
    op.add_column('invoices', sa.Column('payee_party', sa.JSON(), nullable=True))

    # 2. Drop old bill_party (VARCHAR) and add new bill_party (JSON)
    op.drop_column('invoices', 'bill_party')
    op.add_column('invoices', sa.Column('bill_party', sa.JSON(), nullable=True))

    # 3. Drop old ship_party (VARCHAR) and add new ship_party (JSON)
    op.drop_column('invoices', 'ship_party')
    op.add_column('invoices', sa.Column('ship_party', sa.JSON(), nullable=True))

    # 4. Drop old tax_representative_party (VARCHAR) and add new tax_representative_party (JSON)
    op.drop_column('invoices', 'tax_representative_party')
    op.add_column('invoices', sa.Column('tax_representative_party', sa.JSON(), nullable=True))

    # 5. Drop old actual_delivery_date (VARCHAR) and add new actual_delivery_date (Date)
    op.drop_column('invoices', 'actual_delivery_date')
    op.add_column('invoices', sa.Column('actual_delivery_date', sa.Date(), nullable=True))

    # 6. Drop old allowance_charge (INTEGER) and add new allowance_charge (JSON)
    # Note: If there was data in this INTEGER column, it will be lost.
    op.drop_column('invoices', 'allowance_charge')
    op.add_column('invoices', sa.Column('allowance_charge', sa.JSON(), nullable=True))


    # --- INVOICES FOREIGN KEY UPDATE ---
    op.drop_constraint(op.f('invoices_business_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'organisations', ['business_id'], ['business_id'], ondelete='CASCADE')


    # --- ZOHO_INVOICES COLUMN ADDS AND DROPS ---
    op.add_column('zoho_invoices', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('zoho_invoices', sa.Column('accounting_cost', sa.String(), nullable=True))
    op.add_column('zoho_invoices', sa.Column('customer_name', sa.String(), nullable=True))
    op.add_column('zoho_invoices', sa.Column('email', sa.String(), nullable=True))
    op.add_column('zoho_invoices', sa.Column('customer_default_billing_address', sa.JSON(), nullable=True))
    op.drop_column('zoho_invoices', 'customer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema by dropping new columns and adding back old ones."""
    # ### commands auto generated by Alembic - please adjust! ###

    # --- ZOHO_INVOICES COLUMN REVERSAL ---
    op.add_column('zoho_invoices', sa.Column('customer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('zoho_invoices', 'customer_default_billing_address')
    op.drop_column('zoho_invoices', 'email')
    op.drop_column('zoho_invoices', 'customer_name')
    op.drop_column('zoho_invoices', 'accounting_cost')
    op.drop_column('zoho_invoices', 'due_date')


    # --- INVOICES FOREIGN KEY REVERSAL ---
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_business_id_fkey'), 'invoices', 'organisations', ['business_id'], ['business_id'])


    # --- INVOICES TABLE COLUMN DROPS AND ADDS (REVERSAL) ---

    # 1. Drop new payee_party (JSON) and add back old payee_party (VARCHAR)
    op.drop_column('invoices', 'payee_party')
    op.add_column('invoices', sa.Column('payee_party', sa.VARCHAR(), nullable=True))

    # 2. Drop new bill_party (JSON) and add back old bill_party (VARCHAR)
    op.drop_column('invoices', 'bill_party')
    op.add_column('invoices', sa.Column('bill_party', sa.VARCHAR(), nullable=True))

    # 3. Drop new ship_party (JSON) and add back old ship_party (VARCHAR)
    op.drop_column('invoices', 'ship_party')
    op.add_column('invoices', sa.Column('ship_party', sa.VARCHAR(), nullable=True))

    # 4. Drop new tax_representative_party (JSON) and add back old tax_representative_party (VARCHAR)
    op.drop_column('invoices', 'tax_representative_party')
    op.add_column('invoices', sa.Column('tax_representative_party', sa.VARCHAR(), nullable=True))

    # 5. Drop new actual_delivery_date (Date) and add back old actual_delivery_date (VARCHAR)
    op.drop_column('invoices', 'actual_delivery_date')
    op.add_column('invoices', sa.Column('actual_delivery_date', sa.VARCHAR(), nullable=True))

    # 6. Drop new allowance_charge (JSON) and add back old allowance_charge (INTEGER)
    op.drop_column('invoices', 'allowance_charge')
    op.add_column('invoices', sa.Column('allowance_charge', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###