"""update

Revision ID: 276201451902
Revises: 887a870ae8b3
Create Date: 2025-12-13 18:19:58.961572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '276201451902'
down_revision: Union[str, Sequence[str], None] = '887a870ae8b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_maps', sa.Column('retrieve_status', sa.Boolean(), nullable=True))
    op.add_column('invoice_maps', sa.Column('submission_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_maps', 'submission_date')
    op.drop_column('invoice_maps', 'retrieve_status')
    # ### end Alembic commands ###
