"""change email to username

Revision ID: 32228ed85424
Revises: 480f7b419495
Create Date: 2025-12-05 11:25:57.735572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32228ed85424'
down_revision: Union[str, Sequence[str], None] = '480f7b419495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add the new column as NULLABLE (temp stage)
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))

    # 2. Populate the new column for existing rows
    # **CRITICAL STEP:** This assumes you want the initial username to be derived from the email.
    # We strip the domain part (e.g., 'user@example.com' -> 'user').
    op.execute(
        "UPDATE users SET username = SUBSTRING(email FROM 1 FOR POSITION('@' IN email) - 1)"
    )

    # 3. Apply the NOT NULL constraint to enforce it going forward
    op.alter_column('users', 'username', existing_type=sa.String(), nullable=False)

    # 4. Create the unique constraint
    op.create_unique_constraint(None, 'users', ['username'])

    # 5. Drop the old constraint and column
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_column('users', 'email')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
