"""changed currency foreign key

Revision ID: 342a7946b1dc
Revises: 9a690748dc94
Create Date: 2025-12-17 18:56:56.638462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '342a7946b1dc'
down_revision: Union[str, Sequence[str], None] = '9a690748dc94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lga_codes_state_code_fkey'), 'lga_codes', type_='foreignkey')
    op.create_foreign_key(None, 'lga_codes', 'state_codes', ['state_code'], ['code'], ondelete='CASCADE')
    op.drop_constraint(op.f('zoho_invoices_business_id_fkey'), 'zoho_invoices', type_='foreignkey')
    op.create_foreign_key(None, 'zoho_invoices', 'currencies', ['currency_code'], ['code'])
    op.create_foreign_key(None, 'zoho_invoices', 'organisations', ['business_id'], ['business_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zoho_invoices', type_='foreignkey')
    op.drop_constraint(None, 'zoho_invoices', type_='foreignkey')
    op.create_foreign_key(op.f('zoho_invoices_business_id_fkey'), 'zoho_invoices', 'organisations', ['business_id'], ['business_id'])
    op.drop_constraint(None, 'lga_codes', type_='foreignkey')
    op.create_foreign_key(op.f('lga_codes_state_code_fkey'), 'lga_codes', 'state_codes', ['state_code'], ['code'])
    # ### end Alembic commands ###
