"""update send

Revision ID: 480f7b419495
Revises: a94901d1d027
Create Date: 2025-11-28 13:04:55.065166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '480f7b419495'
down_revision: Union[str, Sequence[str], None] = 'a94901d1d027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zoho_invoices', sa.Column('send_treatment', sa.Integer(), nullable=True))
    op.drop_column('zoho_invoices', 'treatment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zoho_invoices', sa.Column('treatment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('zoho_invoices', 'send_treatment')
    # ### end Alembic commands ###
