"""added customer_id to zoho_invoice

Revision ID: 4dac70b0e558
Revises: 1e199ed3442f
Create Date: 2025-11-19 08:20:38.448751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dac70b0e558'
down_revision: Union[str, Sequence[str], None] = '1e199ed3442f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zoho_invoices', sa.Column('customer_id', sa.String(), nullable=True))
    op.add_column('zoho_invoices', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zoho_invoices', 'notes')
    op.drop_column('zoho_invoices', 'customer_id')
    # ### end Alembic commands ###
