"""add invoice status

Revision ID: 5665f6d636ed
Revises: 6581b2e02ff2
Create Date: 2025-11-20 11:15:05.331162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5665f6d636ed'
down_revision: Union[str, Sequence[str], None] = '6581b2e02ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zoho_invoices', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zoho_invoices', 'status')
    # ### end Alembic commands ###
