"""added a new table for invoice metadata

Revision ID: 5e1916a9aad6
Revises: c6cb05828541
Create Date: 2025-11-11 12:22:17.449196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e1916a9aad6'
down_revision: Union[str, Sequence[str], None] = 'c6cb05828541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_submission_status',
    sa.Column('irn', sa.String(), nullable=False),
    sa.Column('submission_status', sa.Boolean(), nullable=True),
    sa.Column('submission_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['irn'], ['invoices.irn'], ),
    sa.PrimaryKeyConstraint('irn'),
    sa.UniqueConstraint('irn')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_submission_status')
    # ### end Alembic commands ###
