"""incorporated line items into invoice table

Revision ID: 6581b2e02ff2
Revises: 4dac70b0e558
Create Date: 2025-11-19 11:09:16.364764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6581b2e02ff2'
down_revision: Union[str, Sequence[str], None] = '4dac70b0e558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zoho_invoices', sa.Column('line_items', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zoho_invoices', 'line_items')
    # ### end Alembic commands ###
