"""add invoice_map

Revision ID: 887a870ae8b3
Revises: d3fe5fe88319
Create Date: 2025-12-12 12:19:41.358482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '887a870ae8b3'
down_revision: Union[str, Sequence[str], None] = 'd3fe5fe88319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zoho_org_id', sa.String(), nullable=False),
    sa.Column('zoho_invoice_number', sa.String(), nullable=False),
    sa.Column('irn', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_maps')
    # ### end Alembic commands ###
