"""initial setup.

Revision ID: 9bc8583f5e4a
Revises: 
Create Date: 2025-11-10 02:31:35.552465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc8583f5e4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol_native', sa.String(), nullable=False),
    sa.Column('decimal_digits', sa.Float(), nullable=False),
    sa.Column('rounding', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name_plural', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name_plural'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('invoice_types',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('rc_number', sa.String(), nullable=False),
    sa.Column('tin', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telephone', sa.String(), nullable=False),
    sa.Column('business_description', sa.String(), nullable=True),
    sa.Column('zoho_org_id', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('org_secret', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('rc_number'),
    sa.UniqueConstraint('tin')
    )
    op.create_table('payment_means',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('product_codes',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code')
    )
    op.create_table('service_codes',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code')
    )
    op.create_table('state_codes',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tax_categories',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vat_exemptions',
    sa.Column('heading_no', sa.Float(), nullable=False),
    sa.Column('harmonized_system_code', sa.Float(), nullable=False),
    sa.Column('tarrif_category', sa.String(), nullable=False),
    sa.Column('tarrif', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('heading_no'),
    sa.UniqueConstraint('heading_no')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('irn', sa.String(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('issue_time', sa.Time(), nullable=True),
    sa.Column('invoice_type_code', sa.String(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('tax_point_date', sa.Date(), nullable=True),
    sa.Column('document_currency_code', sa.String(), nullable=False),
    sa.Column('tax_currency_code', sa.String(), nullable=False),
    sa.Column('accounting_cost', sa.String(), nullable=True),
    sa.Column('buyer_reference', sa.String(), nullable=True),
    sa.Column('invoice_delivery_period', sa.String(), nullable=True),
    sa.Column('order_reference', sa.String(), nullable=True),
    sa.Column('billing_reference', sa.String(), nullable=True),
    sa.Column('dispatch_document_reference', sa.String(), nullable=True),
    sa.Column('receipt_document_reference', sa.String(), nullable=True),
    sa.Column('originator_document_reference', sa.String(), nullable=True),
    sa.Column('contract_document_reference', sa.String(), nullable=True),
    sa.Column('additional_document_reference', sa.String(), nullable=True),
    sa.Column('accounting_customer_party', sa.String(), nullable=True),
    sa.Column('accounting_supplier_party', sa.String(), nullable=True),
    sa.Column('payee_party', sa.String(), nullable=True),
    sa.Column('bill_party', sa.String(), nullable=True),
    sa.Column('ship_party', sa.String(), nullable=True),
    sa.Column('tax_representative_party', sa.String(), nullable=True),
    sa.Column('actual_delivery_date', sa.String(), nullable=True),
    sa.Column('payment_means', sa.String(), nullable=False),
    sa.Column('payment_terms_note', sa.String(), nullable=True),
    sa.Column('allowance_charge', sa.Integer(), nullable=True),
    sa.Column('tax_total', sa.JSON(), nullable=True),
    sa.Column('legal_monetary_total', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('line_items', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['organisations.business_id'], ),
    sa.ForeignKeyConstraint(['document_currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['invoice_type_code'], ['invoice_types.key'], ),
    sa.ForeignKeyConstraint(['payment_means'], ['payment_means.key'], ),
    sa.ForeignKeyConstraint(['tax_currency_code'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('irn')
    )
    op.create_table('lga_codes',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('state_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['state_code'], ['state_codes.code'], ),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('zoho_invoices',
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('currency_code', sa.String(), nullable=False),
    sa.Column('tax_type', sa.String(), nullable=False),
    sa.Column('tax_total', sa.Float(), nullable=False),
    sa.Column('discount_total', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('zoho_org_id', sa.String(), nullable=False),
    sa.Column('sub_total', sa.Float(), nullable=False),
    sa.Column('bcy_discount_total', sa.Float(), nullable=False),
    sa.Column('bcy_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['organisations.business_id'], ),
    sa.PrimaryKeyConstraint('business_id', 'invoice_id'),
    sa.UniqueConstraint('invoice_id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('invoice_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hsn_code', sa.String(), nullable=False),
    sa.Column('product_category', sa.String(), nullable=False),
    sa.Column('isic_code', sa.Integer(), nullable=False),
    sa.Column('service_category', sa.String(), nullable=False),
    sa.Column('discount_rate', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('fee_rate', sa.Float(), nullable=False),
    sa.Column('fee_amount', sa.Float(), nullable=False),
    sa.Column('invoiced_quantity', sa.Float(), nullable=False),
    sa.Column('line_extension_amount', sa.Float(), nullable=False),
    sa.Column('item', sa.JSON(), nullable=False),
    sa.Column('price', sa.JSON(), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.irn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zoho_invoice_line_items',
    sa.Column('invoice_id', sa.String(), nullable=False),
    sa.Column('line_item_id', sa.String(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=True),
    sa.Column('item_type_formatted', sa.String(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('internal_name', sa.String(), nullable=True),
    sa.Column('sales_rate_formatted', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('pricing_scheme', sa.String(), nullable=True),
    sa.Column('pricebook_id', sa.String(), nullable=True),
    sa.Column('bill_id', sa.String(), nullable=True),
    sa.Column('bcy_rate_formatted', sa.String(), nullable=True),
    sa.Column('image_document_id', sa.String(), nullable=True),
    sa.Column('expense_receipt_name', sa.String(), nullable=True),
    sa.Column('item_total', sa.Float(), nullable=True),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('cost_amount', sa.Float(), nullable=True),
    sa.Column('tax_type', sa.String(), nullable=True),
    sa.Column('cost_amount_formatted', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('markup_percent_formatted', sa.String(), nullable=True),
    sa.Column('bcy_rate', sa.Float(), nullable=True),
    sa.Column('item_total_formatted', sa.String(), nullable=True),
    sa.Column('salesorder_item_id', sa.String(), nullable=True),
    sa.Column('discount_account_name', sa.String(), nullable=True),
    sa.Column('rate_formatted', sa.String(), nullable=True),
    sa.Column('header_id', sa.String(), nullable=True),
    sa.Column('discount_account_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('item_order', sa.Float(), nullable=True),
    sa.Column('bill_item_id', sa.String(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('sales_rate', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('tax_name', sa.String(), nullable=True),
    sa.Column('header_name', sa.String(), nullable=True),
    sa.Column('markup_percent', sa.Float(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('tax_percentage', sa.Float(), nullable=True),
    sa.Column('expense_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['zoho_invoices.invoice_id'], ),
    sa.PrimaryKeyConstraint('line_item_id'),
    sa.UniqueConstraint('line_item_id')
    )
    op.create_table('zoho_invoice_line_item_taxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_item_id', sa.String(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('tax_specific_type', sa.String(), nullable=True),
    sa.Column('tax_name', sa.String(), nullable=True),
    sa.Column('tax_amount_formatted', sa.String(), nullable=True),
    sa.Column('tax_percentage', sa.Float(), nullable=False),
    sa.Column('tax_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['line_item_id'], ['zoho_invoice_line_items.line_item_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zoho_invoice_line_item_taxes')
    op.drop_table('zoho_invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_table('zoho_invoices')
    op.drop_table('lga_codes')
    op.drop_table('invoices')
    op.drop_table('vat_exemptions')
    op.drop_table('users')
    op.drop_table('tax_categories')
    op.drop_table('state_codes')
    op.drop_table('service_codes')
    op.drop_table('product_codes')
    op.drop_table('payment_means')
    op.drop_table('organisations')
    op.drop_table('invoice_types')
    op.drop_table('currencies')
    # ### end Alembic commands ###
