"""added org rel with zoho invoice

Revision ID: a94901d1d027
Revises: ddb21b53ed52
Create Date: 2025-11-27 10:02:28.539026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94901d1d027'
down_revision: Union[str, Sequence[str], None] = 'ddb21b53ed52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'product_codes', ['code'])
    op.create_unique_constraint(None, 'service_codes', ['code'])
    op.alter_column('vat_exemptions', 'heading_no',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               autoincrement=True)
    op.create_unique_constraint(None, 'vat_exemptions', ['heading_no'])
    op.create_unique_constraint(None, 'zoho_invoices', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zoho_invoices', type_='unique')
    op.drop_constraint(None, 'vat_exemptions', type_='unique')
    op.alter_column('vat_exemptions', 'heading_no',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'service_codes', type_='unique')
    op.drop_constraint(None, 'product_codes', type_='unique')
    # ### end Alembic commands ###
