"""remove lga unique name constraint

Revision ID: aeb6ffffb5f0
Revises: e39223c6b08b
Create Date: 2025-11-17 00:25:14.561900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeb6ffffb5f0'
down_revision: Union[str, Sequence[str], None] = 'e39223c6b08b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lga_codes_name_key'), 'lga_codes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('lga_codes_name_key'), 'lga_codes', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
