"""add unique constraint to zoho org id

Revision ID: c0fcf3a8f0d7
Revises: aeb6ffffb5f0
Create Date: 2025-11-17 02:07:07.653178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0fcf3a8f0d7'
down_revision: Union[str, Sequence[str], None] = 'aeb6ffffb5f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'organisations', ['zoho_org_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organisations', type_='unique')
    # ### end Alembic commands ###
