"""added secret column for testing

Revision ID: c6cb05828541
Revises: 9bc8583f5e4a
Create Date: 2025-11-10 02:59:49.579063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6cb05828541'
down_revision: Union[str, Sequence[str], None] = '9bc8583f5e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisations', sa.Column('org_secret_plain', sa.String(), nullable=False))
    op.alter_column('organisations', 'org_secret',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'product_codes', ['code'])
    op.create_unique_constraint(None, 'service_codes', ['code'])
    op.alter_column('vat_exemptions', 'heading_no',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               autoincrement=True)
    op.create_unique_constraint(None, 'vat_exemptions', ['heading_no'])
    op.create_unique_constraint(None, 'zoho_invoice_line_item_taxes', ['id'])
    op.create_unique_constraint(None, 'zoho_invoice_line_items', ['line_item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zoho_invoice_line_items', type_='unique')
    op.drop_constraint(None, 'zoho_invoice_line_item_taxes', type_='unique')
    op.drop_constraint(None, 'vat_exemptions', type_='unique')
    op.alter_column('vat_exemptions', 'heading_no',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'service_codes', type_='unique')
    op.drop_constraint(None, 'product_codes', type_='unique')
    op.alter_column('organisations', 'org_secret',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('organisations', 'org_secret_plain')
    # ### end Alembic commands ###
