"""added user role

Revision ID: d3fe5fe88319
Revises: 32228ed85424
Create Date: 2025-12-05 12:05:30.583312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3fe5fe88319'
down_revision: Union[str, Sequence[str], None] = '32228ed85424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Add column as NULLABLE (temporary state)
    op.add_column('users', sa.Column('role', sa.String(), nullable=True,default='user'))
    
    # 2. Populate all existing rows with the required default value
    op.execute("UPDATE users SET role = 'user'")
    
    # 3. Alter the column to enforce NOT NULL
    op.alter_column('users', 'role', existing_type=sa.String(), nullable=False)
    
    # ### end Alembic commands ###
    

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###