"""initial setup

Revision ID: ddb21b53ed52
Revises: 
Create Date: 2025-11-27 09:38:16.924988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb21b53ed52'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_codes',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol_native', sa.String(), nullable=False),
    sa.Column('decimal_digits', sa.Float(), nullable=False),
    sa.Column('rounding', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name_plural', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name_plural'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('invoice_types',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('rc_number', sa.String(), nullable=False),
    sa.Column('tin', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telephone', sa.String(), nullable=False),
    sa.Column('business_description', sa.String(), nullable=True),
    sa.Column('zoho_org_id', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('org_secret', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('rc_number'),
    sa.UniqueConstraint('tin'),
    sa.UniqueConstraint('zoho_org_id')
    )
    op.create_table('payment_means',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('product_codes',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code')
    )
    op.create_table('service_codes',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code')
    )
    op.create_table('state_codes',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tax_categories',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vat_exemptions',
    sa.Column('heading_no', sa.Float(), nullable=False),
    sa.Column('harmonized_system_code', sa.Float(), nullable=False),
    sa.Column('tarrif_category', sa.String(), nullable=False),
    sa.Column('tarrif', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('heading_no'),
    sa.UniqueConstraint('heading_no')
    )
    op.create_table('lga_codes',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('state_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['state_code'], ['state_codes.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('zoho_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=True),
    sa.Column('invoice_id', sa.String(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('currency_code', sa.String(), nullable=False),
    sa.Column('tax_type', sa.String(), nullable=False),
    sa.Column('tax_total', sa.Float(), nullable=False),
    sa.Column('discount_total', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('zoho_org_id', sa.String(), nullable=False),
    sa.Column('line_items', sa.JSON(), nullable=False),
    sa.Column('sub_total', sa.Float(), nullable=False),
    sa.Column('bcy_discount_total', sa.Float(), nullable=False),
    sa.Column('bcy_total', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('accounting_cost', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('customer_default_billing_address', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('send_status', sa.Boolean(), nullable=True),
    sa.Column('treatment', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['organisations.business_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zoho_invoices')
    op.drop_table('lga_codes')
    op.drop_table('vat_exemptions')
    op.drop_table('users')
    op.drop_table('tax_categories')
    op.drop_table('state_codes')
    op.drop_table('service_codes')
    op.drop_table('product_codes')
    op.drop_table('payment_means')
    op.drop_table('organisations')
    op.drop_table('invoice_types')
    op.drop_table('currencies')
    op.drop_table('country_codes')
    # ### end Alembic commands ###
