"""removed the plain secret key column from org

Revision ID: e39223c6b08b
Revises: f0698272529c
Create Date: 2025-11-14 17:46:14.330326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e39223c6b08b'
down_revision: Union[str, Sequence[str], None] = 'f0698272529c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisations', 'org_secret_plain')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisations', sa.Column('org_secret_plain', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
