"""updated invoice party type to JSON

Revision ID: e59b13033e66
Revises: 5e1916a9aad6
Create Date: 2025-11-12 07:08:30.169755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e59b13033e66'
down_revision: Union[str, Sequence[str], None] = '5e1916a9aad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'invoice_submission_status', ['irn'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice_submission_status', type_='unique')
    # ### end Alembic commands ###
